aws_region          = "us-east-1"
environment         = "dev"
project_name        = "terraform-basics"
state_bucket_name   = "terraform-state-management-lab"
dynamodb_table_name = "terraform-state-lock"
vpc_cidr            = "10.0.0.0/16"
subnet_cidr         = "10.0.1.0/24" 